import { Geist, Geist_Mono } from "next/font/google";
import { Great_Vibes, Playfair_Display } from "next/font/google"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// const greatVibes = Great_Vibes({ subsets: ["latin"], weight: "400" });
// const playfair = Playfair_Display({ subsets: ["latin"], weight: "400", style: "italic" });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
